version: "3.8"

services:
  app:
    build: .
    container_name: what-to-watch-app
    working_dir: /app
    ports:
      - "${PORT:-5050}:${PORT:-5050}"
    env_file:
      - .env.prod
    networks:
      - wtwt

networks:
  wtwt:
    driver: bridge
